# Generated by Django 4.2.14 on 2024-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('seat_capacity', models.CharField(max_length=150)),
                ('arrival_time_at_source', models.CharField(max_length=150)),
                ('arrival_time_at_departure', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'trains',
            },
        ),
    ]
