# Generated by Django 4.2.14 on 2024-07-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_train_available_seats_alter_train_seat_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField()),
                ('seat_numbers', models.JSONField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
