# Generated by Django 4.2.14 on 2024-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='USER', max_length=128),
            preserve_default=False,
        ),
    ]
